version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_PORT="3306"
      - DB_HOST="database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:8
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    expose:
      - '33061'
    environment:
      - MYSQL_ROOT_PASSWORD="secret"
      - MYSQL_DATABASE="calendar"
      - MYSQL_USER="user"
      - MYSQL_PASSWORD="secret"

    ports:
        - "33061:3306"

volumes:
  dbdata:
